name: contentgen-demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.1
  - pandas
  - matplotlib
  - jupyterlab
  - requests
  - beautifulsoup4
  - python-dotenv
  - fastapi
  - uvicorn
  - pip
  - pip:
      - coverage==5.5
      - babypandas==0.1.9
      - google-generativeai
      - server-extension
